name: CI

on:
  push:
    branches:
      # - main
  pull_request:
    branches:
      - main

# Flutter actions taken from https://github.com/subosito/flutter-action
jobs:
  api:
    name: Test the Flask API
    environment: test
    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      DEV_DATABASE: ${{ secrets.DEV_DATABASE }}
      IMAGE_DIR: .
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./the_watering_hole/api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python -m pytest

  drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [playstore]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
          channel: 'stable'

      # Run integration test
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Pixel_3a_API_29
          script: flutter drive --target=test_driver/app.dart

#   build-android:
#     name: Run Flutter build and tests on Android
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./the_watering_hole
#     steps:
#     - uses: actions/checkout@v3
#     - uses: actions/setup-java@v2
#       with:
#         distribution: 'zulu'
#         java-version: '11'
#     - uses: subosito/flutter-action@v2
#       with:
#         flutter-version: '3.0.5'
#     - run: flutter pub get
#     - run: flutter test
#     - run: flutter build apk
#     - run: flutter build appbundle

#   build-ios:
#     name: Run Flutter build and tests on iOS
#     runs-on: macos-latest
#     defaults:
#       run:
#         working-directory: ./the_watering_hole
#     steps:
#     - uses: actions/checkout@v3
#     - uses: subosito/flutter-action@v2
#       with:
#         channel: 'stable'
#         architecture: x64
#     - run: flutter pub get
#     - run: flutter test
#     - run: flutter build ios --release --no-codesign
