name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Flutter actions taken from https://github.com/subosito/flutter-action
jobs:
  api:
    name: Test the Flask API
    environment: test
    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      DEV_DATABASE: ${{ secrets.DEV_DATABASE }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./the_watering_hole/api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python -m pytest --cov=api --cov-report=xml test/
      - uses: actions/upload-artifact@v2
        with:
          path: coverage.xml

#   build-android:
#     name: Run Flutter build and tests on Android
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./the_watering_hole
#     steps:
#     - uses: actions/checkout@v3
#     - uses: actions/setup-java@v2
#       with:
#         distribution: 'zulu'
#         java-version: '11'
#     - uses: subosito/flutter-action@v2
#       with:
#         flutter-version: '3.0.5'
#     - run: flutter pub get
#     - run: flutter test
#     - run: flutter build apk
#     - run: flutter build appbundle

#   build-ios:
#     name: Run Flutter build and tests on iOS
#     runs-on: macos-latest
#     defaults:
#       run:
#         working-directory: ./the_watering_hole
#     steps:
#     - uses: actions/checkout@v3
#     - uses: subosito/flutter-action@v2
#       with:
#         channel: 'stable'
#         architecture: x64
#     - run: flutter pub get
#     - run: flutter test
#     - run: flutter build ios --release --no-codesign
