name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api:
    name: Test the Flask API
    environment: test
    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      DEV_DATABASE: ${{ secrets.DEV_DATABASE }}
      IMAGE_DIR: .
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./the_watering_hole/api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python -m pytest