name: CodeCov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codecov-flask:
    name: Run CodeCov on Flask API
    environment: test
    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      DEV_DATABASE: ${{ secrets.DEV_DATABASE }}
    defaults:
      run:
        working-directory: ./the_watering_hole/api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python -m pytest --cov=api --cov-report=xml test/
      - uses: actions/upload-artifact@v2
        with:
          path: coverage.xml
      - uses: actions/download-artifact@v2
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  # TODO set up codecov-flutter once the app is developed
